server:
  port: 12345

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ip?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Lvbin@48777742
    druid:
      initialSize: 1
      maxActive: 20
      minIdle: 1
      maxWait: 60000
      poolPreparedStatements: true
      filters: stat,wall,log4j2,log4j,slf4j
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: lvbin
        login-password: lvbin
      filter:
        wall:
          enabled: true
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.lvbin.server

logging:
  level:
    com:
      lvbin:
        server:
          SysUserMapper: Debug